### ISSUE TITLE
[translate] dependency.textile - pjquero

### ISSUE THREAD

**Issue by pjquero** [opensas/playdoces#103]
Traduciendo la guía dependency de la Documentación

**Comment by opensas** [comment]
Ojo, me parece que esa ya la tradujo flor

https://github.com/opensas/playdoces/commit/babda8a17706398e86277deba71d2a284e062f34

**Comment by opensas** [comment]
fijate este ticket

https://github.com/opensas/playdoces/issues/100

**Comment by pjquero** [comment]
Ya!! Creí haber visto el ticket pero como no vi la actualización en el sitio. Bueno no llevaba mucho adelantado.

Gracias :D
