### ISSUE TITLE
[translate] guide5 - DONE - 

### ISSUE THREAD

**Issue by flormontanari** [opensas/playdoces#66]
la guia 5 ya fue traducida

https://github.com/opensas/playdoces/commit/c2b349cefaedb8d19fa08a75ca4df692ac31ed25

**Comment by opensas** [comment]
qu tal flor!

ojo que la guia 5 y 6 ya estn traducidas!!!

https://github.com/opensas/playdoces/blob/master/documentation/1.2.4/manual/guide5.textile
http://playdoces.appspot.com/documentation/1.2.4/guide5

http://playdoces.appspot.com/documentation/1.2.4/guide6

si quers arranc con la 7 que hasta ah llegamos...
http://playdoces.appspot.com/documentation/1.2.4/guide7

despues avisame si queres que nos reunamos con tus compaeros as les
mostramos un poquito de play!

saludsos

sas

On Mon, Jan 2, 2012 at 2:16 PM, flormontanari <
reply@reply.github.com
