### ISSUE TITLE
[translate] guide7

### ISSUE THREAD

**Issue by flormontanari** [opensas/playdoces#68]

**Comment by opensas** [comment]
s seor, dale para adelante noms!!!

prometo que ese no lo traduzco

vamos a ver si terminamos enero con la gua de YABE traducida

saludos

sas

pd: avisame cuando quieras que hablemos con tus amigos... salvmoslos de
struts!!!

On Tue, Jan 3, 2012 at 9:26 PM, flormontanari <
reply@reply.github.com
