### ISSUE TITLE
[requirement] agregarse como colaborador en la página about - trapagual

### ISSUE THREAD

**Issue by opensas** [opensas/playdoces#79]
vamos! que bien merecido lo tienes!

http://playdoces.appspot.com/about

views/Application/es/about.html

**Comment by trapagual** [comment]
Me lo he leído, telojuro. ¿Es obligatorio darse de alta?
Perdón... soy nuevo ;-)

**Comment by opensas** [comment]
no, claro que no, simplemente como reconocimiento al tiempo y el esfuerzo
dedicado... pero no es obligatorio en absoluto ;-)

saludos

sas

On Mon, Jan 9, 2012 at 11:12 AM, Walt <
reply@reply.github.com
