### ISSUE TITLE
Corrección en la presentación de Play! 2.0

### ISSUE THREAD

**Issue by alfonsokim** [opensas/playdoces#82]
La presentación de Play! 2.0 contiene un pequeño error: Dice "Contruido pensando asincrónicamente".
/es/introduce20.html [alfonsokim]

**Comment by opensas** [comment]
qué raro, ese error lo había corregido los primeros días de noviembre, es raro que todavía te figure... podrías fijarte de vuelta? http://playdoces.appspot.com/2.0...

posiblemente limpiando el cache del explorador...
